-- task_2.sql
-- Create all tables for alx_book_store

USE alx_book_store;

-- AUTHORS table
CREATE TABLE IF NOT EXISTS AUTHORS (
  AUTHOR_ID INT NOT NULL AUTO_INCREMENT,
  AUTHOR_NAME VARCHAR(215) NOT NULL,
  PRIMARY KEY (AUTHOR_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

-- BOOKS table
CREATE TABLE IF NOT EXISTS BOOKS (
  BOOK_ID INT NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(130) NOT NULL,
  AUTHOR_ID INT NOT NULL,
  PRICE DOUBLE NOT NULL,
  PUBLICATION_DATE DATE,
  PRIMARY KEY (BOOK_ID),
  INDEX IDX_BOOKS_AUTHOR_ID (AUTHOR_ID),
  CONSTRAINT FK_BOOKS_AUTHOR
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

-- CUSTOMERS table
CREATE TABLE IF NOT EXISTS CUSTOMERS (
  CUSTOMER_ID INT NOT NULL AUTO_INCREMENT,
  CUSTOMER_NAME VARCHAR(215) NOT NULL,
  EMAIL VARCHAR(215) NOT NULL UNIQUE,
  ADDRESS TEXT,
  PRIMARY KEY (CUSTOMER_ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

-- ORDERS table
CREATE TABLE IF NOT EXISTS ORDERS (
  ORDER_ID INT NOT NULL AUTO_INCREMENT,
  CUSTOMER_ID INT NOT NULL,
  ORDER_DATE DATE NOT NULL,
  PRIMARY KEY (ORDER_ID),
  INDEX IDX_ORDERS_CUSTOMER_ID (CUSTOMER_ID),
  CONSTRAINT FK_ORDERS_CUSTOMER
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

-- ORDER_DETAILS table
CREATE TABLE IF NOT EXISTS ORDER_DETAILS (
  ORDERDETAILID INT NOT NULL AUTO_INCREMENT,
  ORDER_ID INT NOT NULL,
  BOOK_ID INT NOT NULL,
  QUANTITY DOUBLE NOT NULL,
  PRIMARY KEY (ORDERDETAILID),
  INDEX IDX_OD_ORDER_ID (ORDER_ID),
  INDEX IDX_OD_BOOK_ID (BOOK_ID),
  CONSTRAINT FK_OD_ORDER
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT FK_OD_BOOK
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;
